baseurl = "https://www.cs.ox.ac.uk/projects/PINTS/"
languageCode = "en-gb"
title = "Parametrising biological models with PINTS"
theme = "natrium"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsUseClasses = true
pygmentsCodefences = true
googleAnalytics = "UA-48149829-6"
enableGitInfo = true

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "Functional testing"
    url = "/functional-testing/"
    weight = -150

[[menu.main]]
    name = "People"
    url = "/people/"
    weight = -140

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = -110

[params]
    description = ""

    [params.logo]
    url = "pints-logo.svg"
    alt = "PINTS"